module.exports = {
  VISITED_BLOG_POST: 'VISITED_BLOG_POST',
  FAVORITED_BLOG_POST: 'FAVORITED_BLOG_POST',
  REVISED_BLOG_POST: 'REVISED_BLOG_POST',
  FAVORITED_PRODUCT: 'FAVORITED_PRODUCT',
  REVISED_PRODUCT: 'REVISED_PRODUCT',
  VISITED_PRODUCT: 'VISITED_PRODUCT',
  VISITED_USER_PROFILE: 'VISITED_USER_PROFILE',
  FAVORITED_USER_PROFILE: 'FAVORITED_USER_PROFILE',
};
