const itemTypes = {
  VISITED_BLOG_POST: 'VISITED_BLOG_POST',
  FAVORITED_BLOG_POST: 'FAVORITED_BLOG_POST',
  REVISED_BLOG_POST: 'REVISED_BLOG_POST',
  FAVORITED_PRODUCT: 'FAVORITED_PRODUCT',
  REVISED_PRODUCT: 'REVISED_PRODUCT',
  VISITED_PRODUCT: 'VISITED_PRODUCT',
  VISITED_USER: 'VISITED_USER',
  FAVORITED_USER: 'FAVORITED_USER',
  REVISED_USER: 'REVISED_USER',
};

const categories = {
  PRODUCT: 'PRODUCT',
  USER: 'USER',
  'BLOG-POST': 'BLOG_POST',
};

const origin = {
  FAVORITE: 'FAVORITED',
  REVIEW: 'REVISED',
  VISIT: 'VISITED',
};

module.exports = {
  itemTypes,
  categories,
  origin,
};
